const CHANGE_PROJECT_TITLE = "CHANGE_PROJECT_TITLE";
const ADD_OBJECT = "ADD_OBJECT";
const ADD_OBJECT_TO_PAGE = "ADD_OBJECT_TO_PAGE";
module.exports = { CHANGE_PROJECT_TITLE, ADD_OBJECT, ADD_OBJECT_TO_PAGE };
